# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
#after-startup-command = [
#  'exec-and-forget borders style=round hidpi=true active_color=0xffe1e3e4 width=4.0'
#]

after-startup-command = [
  'exec-and-forget borders style=round hidpi=false width=8.0 active_color=0xff4c7899 inactive_color=0xff333333'
]


# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = false

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 16 
inner.vertical =   16 
outer.left =       14
outer.bottom =     14
outer.top =        14 
outer.right =      14

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
#cmd-enter = '''exec-and-forget osascript -e '
#tell application "Ghostty"
#    activate
#end tell
#tell application "System Events"
#    keystroke "n" using {command down}
#end tell'
#'''
#cmd-enter = '''exec-and-forget osascript -e '
#tell application "iTerm"
#    create window with default profile
#    activate
#end tell'
#'''

cmd-enter = 'exec-and-forget open -n -a WezTerm'

cmd-shift-enter = 'exec-and-forget open -n -a WezTerm'

#cmd-e = 'exec-and-forget open -a /Applications/Finder.app'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
cmd-alt-s = 'layout h_accordion'
cmd-alt-e = 'layout tiles horizontal vertical'
alt-shift-space = 'layout floating tiling'
#cmd-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
cmd-h = 'focus --boundaries all-monitors-outer-frame left'
cmd-j = 'focus --boundaries all-monitors-outer-frame down'
cmd-k = 'focus --boundaries all-monitors-outer-frame up'
cmd-l = 'focus --boundaries all-monitors-outer-frame right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
cmd-shift-h = 'move left'
cmd-shift-j = 'move down'
cmd-shift-k = 'move up'
cmd-shift-l = 'move right'

## splits
cmd-alt-h = 'split horizontal'
cmd-alt-v = 'split vertical'

cmd-shift-f = 'fullscreen'
cmd-shift-q = 'close'



# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'
cmd-5 = 'workspace 5'
cmd-6 = 'workspace 6'
cmd-7 = 'workspace 7'
cmd-8 = 'workspace 8'
cmd-9 = 'workspace 9'
cmd-0 = 'workspace 10'
#alt-a = 'workspace A' # In your config, you can drop workspace bindings that you don't need
#alt-b = 'workspace B'
#alt-c = 'workspace C'
#alt-d = 'workspace D'
#alt-e = 'workspace E'
#alt-f = 'workspace F'
#alt-g = 'workspace G'
#alt-i = 'workspace I'
#alt-m = 'workspace M'
#alt-n = 'workspace N'
#alt-o = 'workspace O'
#alt-p = 'workspace P'
#alt-q = 'workspace Q'
#alt-r = 'workspace R'
#alt-s = 'workspace S'
#alt-t = 'workspace T'
#alt-u = 'workspace U'
#alt-v = 'workspace V'
#alt-w = 'workspace W'
#alt-x = 'workspace X'
#alt-y = 'workspace Y'
#alt-z = 'workspace Z'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
cmd-shift-1 = 'move-node-to-workspace 1'
cmd-shift-2 = 'move-node-to-workspace 2'
cmd-shift-3 = 'move-node-to-workspace 3'
cmd-shift-4 = 'move-node-to-workspace 4'
cmd-shift-5 = 'move-node-to-workspace 5'
cmd-shift-6 = 'move-node-to-workspace 6'
cmd-shift-7 = 'move-node-to-workspace 7'
cmd-shift-8 = 'move-node-to-workspace 8'
cmd-shift-9 = 'move-node-to-workspace 9'
cmd-shift-0 = 'move-node-to-workspace 10'
#alt-shift-a = 'move-node-to-workspace A'
#alt-shift-b = 'move-node-to-workspace B'
#alt-shift-c = 'move-node-to-workspace C'
#alt-shift-d = 'move-node-to-workspace D'
#alt-shift-e = 'move-node-to-workspace E'
#alt-shift-f = 'move-node-to-workspace F'
#alt-shift-g = 'move-node-to-workspace G'
#alt-shift-i = 'move-node-to-workspace I'
#alt-shift-m = 'move-node-to-workspace M'
#alt-shift-n = 'move-node-to-workspace N'
#alt-shift-o = 'move-node-to-workspace O'
#alt-shift-p = 'move-node-to-workspace P'
#alt-shift-q = 'move-node-to-workspace Q'
#alt-shift-r = 'move-node-to-workspace R'
#alt-shift-s = 'move-node-to-workspace S'
#alt-shift-t = 'move-node-to-workspace T'
#alt-shift-u = 'move-node-to-workspace U'
#alt-shift-v = 'move-node-to-workspace V'
#alt-shift-w = 'move-node-to-workspace W'
#alt-shift-x = 'move-node-to-workspace X'
#alt-shift-y = 'move-node-to-workspace Y'
#alt-shift-z = 'move-node-to-workspace Z'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
cmd-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
cmd-shift-right = 'move-workspace-to-monitor --wrap-around next'
cmd-shift-left = 'move-workspace-to-monitor --wrap-around prev'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
cmd-shift-s = 'mode service'
cmd-r = 'mode resize'



cmd-shift-r = 'reload-config'

#cmd-left-click = 'move start'
#cmd-right-click = 'resize start'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'
cmd-h = []
cmd-alt-h = []

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

# sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#s = ['layout sticky tiling', 'mode main']

cmd-shift-h = ['join-with left', 'mode main']
cmd-shift-j = ['join-with down', 'mode main']
cmd-shift-k = ['join-with up', 'mode main']
cmd-shift-l = ['join-with right', 'mode main']
cmd-h = []
cmd-alt-h = []

down = 'volume down'
up = 'volume up'
shift-down = ['volume set 0', 'mode main']

# some application to workspace binds
[[on-window-detected]]
#if.app-id = 'net.whatsapp.Whatsapp'
if.app-name-regex-substring = 'Whatsapp'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'org.whispersystems.signal-desktop'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'org.keepassxc.keepassxc'
run = 'move-node-to-workspace 8'

[[on-window-detected]]
if.app-id = 'com.spotify.Client'
run = 'move-node-to-workspace 6'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace 10'

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'preview'
run = 'layout floating'

[workspace-to-monitor-force-assignment]
10 = '^Built-in Retina Display$'
